/**
 * QQ 风格"小黄脸"表情映射到 Unicode emoji
 */
export const EMOJI_LIST = [
  { name: '微笑',   char: '😊' },
  { name: '呲牙',   char: '😁' },
  { name: '捂嘴笑', char: '🤭' },
  { name: '调皮',   char: '😏' },
  { name: '酷',     char: '😎' },
  { name: '得意',   char: '😌' },
  { name: '愉快',   char: '😄' },
  { name: '眨眼',   char: '😉' },
  { name: '流汗',   char: '😅' },
  { name: '笑哭',   char: '😂' },
  { name: '笑死',   char: '🤣' },
  { name: '大哭',   char: '😭' },
  { name: '流泪',   char: '😢' },
  { name: '发怒',   char: '😡' },
  { name: '不爽',   char: '😠' },
  { name: '尴尬',   char: '😬' },
  { name: '害羞',   char: '😳' },
  { name: '困',     char: '😴' },
  { name: '生病',   char: '🤒' },
  { name: '惊讶',   char: '😮' },
  { name: '晕',     char: '😵' },
  { name: '爱慕',   char: '😍' },
  { name: '亲亲',   char: '😘' },
  { name: '吐舌',   char: '😜' },
  { name: '苦涩',   char: '😣' },
  { name: '无奈',   char: '🥺' },
  { name: '痛苦',   char: '😖' },
  { name: '恐惧',   char: '😨' },
  { name: '焦虑',   char: '😰' },
  { name: '惊恐',   char: '😱' },
  { name: '拥抱',   char: '🤗' },
  { name: '再见',   char: '👋' },
  { name: 'OK',     char: '👌' },
  { name: '肌肉',   char: '💪' },
  { name: '祈祷',   char: '🙏' },
  { name: '胜利',   char: '✌️' },
  { name: '握手',   char: '🤝' },
  { name: '赞',     char: '👍' },
  { name: '踩',     char: '👎' },
  { name: '庆祝',   char: '🎉' },
];
