/**
 * Unicode emoji groups for the message picker.
 */
export const EMOJI_GROUPS = [
  {
    id: 'classic',
    label: '经典',
    icon: '😊',
    items: [
      { name: '微笑', char: '😊' },
      { name: '呲牙', char: '😁' },
      { name: '大笑', char: '😆' },
      { name: '愉快', char: '😄' },
      { name: '眯眼笑', char: '😄' },
      { name: '笑哭', char: '😂' },
      { name: '笑死', char: '🤣' },
      { name: '眨眼', char: '😉' },
      { name: '调皮', char: '😏' },
      { name: '吐舌', char: '😜' },
      { name: '吐舌笑', char: '😝' },
      { name: '鬼脸', char: '🤪' },
      { name: '酷', char: '😎' },
      { name: '得意', char: '😌' },
      { name: '满足', char: '☺️' },
      { name: '害羞笑', char: '😇' },
      { name: '偷笑', char: '🤭' },
      { name: '捂嘴', char: '🤭' },
      { name: '偷看', char: '🙈' },
      { name: '拥抱', char: '🤗' },
      { name: '思考', char: '🤔' },
      { name: '认真', char: '🙂' },
      { name: '怀疑', char: '🤨' },
      { name: '单片眼镜', char: '🧐' },
      { name: '闭嘴', char: '🤐' },
      { name: '无语', char: '😐' },
      { name: '冷漠', char: '😑' },
      { name: '尴尬', char: '😬' },
      { name: '翻白眼', char: '🙄' },
      { name: '惊讶', char: '😮' },
      { name: '震惊', char: '😲' },
      { name: '脸红', char: '😳' },
      { name: '无奈', char: '🥺' },
      { name: '流汗', char: '😅' },
      { name: '冷汗', char: '😓' },
      { name: '困', char: '😴' },
      { name: '睡着', char: '💤' },
      { name: '晕', char: '😵' },
      { name: '头晕', char: '🥴' },
      { name: '放空', char: '😶' },
      { name: '钱眼', char: '🤑' },
      { name: '流口水', char: '🤤' },
      { name: '机器人', char: '🤖' },
    ],
  },
  {
    id: 'cute',
    label: '可爱',
    icon: '🥰',
    items: [
      { name: '卖萌', char: '🥰' },
      { name: '爱慕', char: '😍' },
      { name: '花痴', char: '🤩' },
      { name: '亲亲', char: '😘' },
      { name: '亲吻', char: '😗' },
      { name: '闭眼亲', char: '😚' },
      { name: '可怜', char: '🥺' },
      { name: '撒娇', char: '🥺' },
      { name: '害羞', char: '😳' },
      { name: '害羞笑', char: '☺️' },
      { name: '开心', char: '😋' },
      { name: '甜笑', char: '😊' },
      { name: '调皮眨眼', char: '😜' },
      { name: '眯眼吐舌', char: '😝' },
      { name: '俏皮', char: '🤪' },
      { name: '安静', char: '🤫' },
      { name: '偷偷看', char: '🙈' },
      { name: '暖心', char: '💗' },
      { name: '比心', char: '💕' },
      { name: '心花', char: '💖' },
      { name: '心动', char: '💓' },
      { name: '双心', char: '💕' },
      { name: '旋转心', char: '💞' },
      { name: '飞吻', char: '💋' },
      { name: '闪亮', char: '✨' },
      { name: '星星眼', char: '🤩' },
      { name: '小花', char: '🌸' },
      { name: '樱花', char: '🌸' },
      { name: '玫瑰', char: '🌹' },
      { name: '彩虹', char: '🌈' },
      { name: '糖果', char: '🍬' },
      { name: '棒棒糖', char: '🍭' },
      { name: '蛋糕', char: '🎂' },
      { name: '礼物', char: '🎁' },
      { name: '气球', char: '🎈' },
    ],
  },
  {
    id: 'mood',
    label: '态度',
    icon: '😤',
    items: [
      { name: '发怒', char: '😡' },
      { name: '不爽', char: '😠' },
      { name: '哼', char: '😤' },
      { name: '爆炸', char: '🤯' },
      { name: '恶魔笑', char: '😈' },
      { name: '小丑', char: '🤡' },
      { name: '哭笑不得', char: '😅' },
      { name: '崩溃', char: '😫' },
      { name: '累了', char: '😩' },
      { name: '苦涩', char: '😣' },
      { name: '痛苦', char: '😖' },
      { name: '委屈', char: '😟' },
      { name: '担心', char: '😥' },
      { name: '难过', char: '☹️' },
      { name: '流泪', char: '😢' },
      { name: '大哭', char: '😭' },
      { name: '焦虑', char: '😰' },
      { name: '恐惧', char: '😨' },
      { name: '惊恐', char: '😱' },
      { name: '脸热', char: '🥵' },
      { name: '冷', char: '🥶' },
      { name: '生病', char: '🤒' },
      { name: '口罩', char: '😷' },
      { name: '受伤', char: '🤕' },
      { name: '恶心', char: '🤢' },
      { name: '呕吐', char: '🤮' },
      { name: '打喷嚏', char: '🤧' },
      { name: '晕乎', char: '😵' },
      { name: '裂开', char: '😩' },
      { name: '冒烟', char: '😤' },
      { name: '吐气', char: '😮' },
      { name: '斜眼', char: '😒' },
      { name: '沉默', char: '😶' },
      { name: '空白', char: '😶' },
      { name: '迷惑', char: '😕' },
      { name: '失望', char: '😞' },
      { name: '懊恼', char: '😔' },
      { name: '困惑', char: '😕' },
      { name: '坚持', char: '😤' },
    ],
  },
  {
    id: 'hands',
    label: '手势',
    icon: '👍',
    items: [
      { name: '再见', char: '👋' },
      { name: '赞', char: '👍' },
      { name: '踩', char: '👎' },
      { name: 'OK', char: '👌' },
      { name: '胜利', char: '✌️' },
      { name: '比心', char: '💕' },
      { name: '爱心手', char: '💗' },
      { name: '鼓掌', char: '👏' },
      { name: '双手', char: '🤲' },
      { name: '祈祷', char: '🙏' },
      { name: '肌肉', char: '💪' },
      { name: '握手', char: '🤝' },
      { name: '指上', char: '☝️' },
      { name: '指右', char: '👉' },
      { name: '指左', char: '👈' },
      { name: '指下', char: '👇' },
      { name: '举手', char: '🙋' },
      { name: '双手举起', char: '🙌' },
      { name: '击掌', char: '🙏' },
      { name: '拳头', char: '✊' },
      { name: '加油拳', char: '👊' },
      { name: '向左拳', char: '🤛' },
      { name: '向右拳', char: '🤜' },
      { name: '手掌', char: '✋' },
      { name: '抬手', char: '🤚' },
      { name: '挥手掌', char: '🖐️' },
      { name: '手写', char: '✍️' },
      { name: '捏一点', char: '🤏' },
      { name: '交叉手指', char: '🤞' },
      { name: '摇滚', char: '🤘' },
      { name: '我爱你', char: '🤟' },
      { name: '打招呼', char: '🖖' },
      { name: '手背指上', char: '👆' },
      { name: '手掌向上', char: '🤲' },
      { name: '手掌向下', char: '👇' },
      { name: '左推', char: '👈' },
      { name: '右推', char: '👉' },
      { name: '眼睛', char: '👀' },
      { name: '嘴唇', char: '👄' },
      { name: '脑子', char: '🧠' },
    ],
  },
  {
    id: 'party',
    label: '心意',
    icon: '🎉',
    items: [
      { name: '爱心', char: '❤️' },
      { name: '橙心', char: '🧡' },
      { name: '黄心', char: '💛' },
      { name: '绿心', char: '💚' },
      { name: '蓝心', char: '💙' },
      { name: '紫心', char: '💜' },
      { name: '黑心', char: '🖤' },
      { name: '白心', char: '🤍' },
      { name: '棕心', char: '🤎' },
      { name: '粉心', char: '💗' },
      { name: '浅蓝心', char: '💙' },
      { name: '灰心', char: '🤍' },
      { name: '心动', char: '💓' },
      { name: '闪心', char: '💖' },
      { name: '双心', char: '💕' },
      { name: '旋转心', char: '💞' },
      { name: '火心', char: '💖' },
      { name: '修补心', char: '💝' },
      { name: '破碎', char: '💔' },
      { name: '火', char: '🔥' },
      { name: '星星', char: '⭐' },
      { name: '闪光', char: '✨' },
      { name: '一百分', char: '💯' },
      { name: '庆祝', char: '🎉' },
      { name: '礼花', char: '🎊' },
      { name: '彩带', char: '🎀' },
      { name: '奖杯', char: '🏆' },
      { name: '奖牌', char: '🏅' },
      { name: '皇冠', char: '👑' },
      { name: '钻石', char: '💎' },
      { name: '玫瑰', char: '🌹' },
      { name: '花束', char: '💐' },
      { name: '太阳', char: '☀️' },
      { name: '月亮', char: '🌙' },
      { name: '彩虹', char: '🌈' },
      { name: '礼物', char: '🎁' },
      { name: '气球', char: '🎈' },
      { name: '派对脸', char: '🥳' },
      { name: '胜利花', char: '🎖️' },
      { name: '烟花', char: '🎆' },
    ],
  },
  {
    id: 'daily',
    label: '日常',
    icon: '💡',
    items: [
      { name: '咖啡', char: '☕' },
      { name: '可乐', char: '🥤' },
      { name: '水杯', char: '🥛' },
      { name: '蛋糕', char: '🎂' },
      { name: '披萨', char: '🍕' },
      { name: '汉堡', char: '🍔' },
      { name: '薯条', char: '🍟' },
      { name: '拉面', char: '🍜' },
      { name: '寿司', char: '🍣' },
      { name: '米饭', char: '🍚' },
      { name: '便当', char: '🍱' },
      { name: '甜甜圈', char: '🍩' },
      { name: '饼干', char: '🍪' },
      { name: '巧克力', char: '🍫' },
      { name: '糖果', char: '🍬' },
      { name: '冰淇淋', char: '🍦' },
      { name: '手机', char: '📱' },
      { name: '电脑', char: '💻' },
      { name: '键盘', char: '⌨️' },
      { name: '电话', char: '📞' },
      { name: '邮件', char: '✉️' },
      { name: '相机', char: '📷' },
      { name: '闹钟', char: '⏰' },
      { name: '日历', char: '📅' },
      { name: '书', char: '📖' },
      { name: '笔记', char: '📝' },
      { name: '铅笔', char: '✏️' },
      { name: '剪刀', char: '✂️' },
      { name: '灯泡', char: '💡' },
      { name: '锁', char: '🔒' },
      { name: '钥匙', char: '🔑' },
      { name: '放大镜', char: '🔍' },
      { name: '沙漏', char: '⏳' },
      { name: '铃铛', char: '🔔' },
      { name: '标签', char: '🏷️' },
      { name: '图钉', char: '📌' },
      { name: '剪贴板', char: '📋' },
      { name: '文件夹', char: '📁' },
      { name: '工具', char: '🛠️' },
    ],
  },
  {
    id: 'symbols',
    label: '符号',
    icon: '✅',
    items: [
      { name: '勾', char: '✅' },
      { name: '叉', char: '❌' },
      { name: '警告', char: '⚠️' },
      { name: '禁止', char: '🚫' },
      { name: '问号', char: '❓' },
      { name: '感叹号', char: '❗' },
      { name: '加一', char: '➕' },
      { name: '减一', char: '➖' },
      { name: '乘号', char: '✖️' },
      { name: '除号', char: '➗' },
      { name: '上箭头', char: '⬆️' },
      { name: '下箭头', char: '⬇️' },
      { name: '左箭头', char: '⬅️' },
      { name: '右箭头', char: '➡️' },
      { name: '返回', char: '↩️' },
      { name: '循环', char: '🔁' },
      { name: '刷新', char: '🔄' },
      { name: '播放', char: '▶️' },
      { name: '暂停', char: '⏸️' },
      { name: '停止', char: '⏹️' },
      { name: '录制', char: '⏺️' },
      { name: '置顶', char: '🔝' },
      { name: '新', char: '🆕' },
      { name: '免费', char: '🆓' },
      { name: '热', char: '♨️' },
      { name: '井号', char: '#️⃣' },
      { name: '零', char: '0️⃣' },
      { name: '一', char: '1️⃣' },
      { name: '二', char: '2️⃣' },
      { name: '三', char: '3️⃣' },
      { name: '四', char: '4️⃣' },
      { name: '五', char: '5️⃣' },
      { name: '六', char: '6️⃣' },
      { name: '七', char: '7️⃣' },
      { name: '八', char: '8️⃣' },
      { name: '九', char: '9️⃣' },
      { name: '十', char: '🔟' },
      { name: '无限', char: '♾️' },
      { name: '版权', char: '©️' },
      { name: '注册', char: '®️' },
    ],
  },
];

export const EMOJI_LIST = EMOJI_GROUPS.flatMap((group) => group.items);
